### ISSUE TITLE
Clarification Needed: Order of Volume Images Generation Relative to Nodules in bbox_annos.xls File

### ISSUE THREAD

**Issue by ibtihal05** [DigCS/Luna-16-nodules-volume#2]
Hi there! I'm currently working on a nodules classification (malignant/benign) project, and I found your cropped dataset to be very useful for my research. However, to utilize it effectively, I need the nodule class information to train my model. I've successfully extracted classification labels from the original LUNA16 dataset based on the patient IDs provided in the bbox_annos file.
However, to ensure accuracy, I need clarification on whether the volume images are generated in the same order as the nodules' order in the bbox_annos.xls file. This is crucial for matching the classification labels with the corresponding volume images.
Could someone confirm whether the volume images are indeed generated in the same order as the nodules' order in the annotation file? This information will greatly aid in maintaining data integrity and facilitating further analysis.
Thank you for your assistance!

**Comment by DigCS** [comment]
> Hi there! I'm currently working on a nodules classification (malignant/benign) project, and I found your cropped dataset to be very useful for my research. However, to utilize it effectively, I need the nodule class information to train my model. I've successfully extracted classification labels from the original LUNA16 dataset based on the patient IDs provided in the bbox_annos file. However, to ensure accuracy, I need clarification on whether the volume images are generated in the same order as the nodules' order in the bbox_annos.xls file. This is crucial for matching the classification labels with the corresponding volume images. Could someone confirm whether the volume images are indeed generated in the same order as the nodules' order in the annotation file? This information will greatly aid in maintaining data integrity and facilitating further analysis. Thank you for your assistance!
